### ISSUE TITLE
LM ascent pad with TIG 0h0mim0seg

### ISSUE THREAD

**Issue by RL77** [orbiternassp/NASSP#513] opened 2020-01-30 00:52 UTC
Hello,

I landed yesterday on the moon with apollo 11. The first ascent pad before we shut down LM appears with the tig 0h0mim0seg:

https://puu.sh/F57OK/5ef3bdd822.png

First time i saw it happen. Just  hope it doesn't happen with the ascension pad after EVA. Update1483

Thank you

**Comment by indy91** [comment] 2020-01-30 13:04
This Ascent PAD calculation still works in the "Apollo 11 - 13 - After Landing T+103h10min" scenario that comes with NASSP. Can you provide your scenario before this calculation? Then I can try and debug it.

**Comment by RL77** [comment] 2020-01-30 14:11
Hello yes, I will send you the file soon.

**Comment by RL77** [comment] 2020-01-30 15:11
Helllo, here the link were you can dowload  the file: If you have any problem just tell me:
 https://drive.google.com/open?id=1UT8EGppOFQg_-BgqCVqgABl8vyD05JOu

Thanks

**Comment by indy91** [comment] 2020-01-30 16:34
Hmm, the Ascent PAD calculation works fine for me. I am not on the same revision as you (have some local updates), but they shouldn't make the difference. I have tried it both by advancing the MCC state in the debug menu and by using time acceleration to get to the time when the PAD is getting calculated.

Just so we are doing the exact same thing, in that scenario you gave me, try advancing the MCC state a few times under "9: Debug Options" and "4: Inc State". Does that also result in you getting the zeros on the Ascent PAD?

**Comment by RL77** [comment] 2020-01-30 17:15
I did as you said, here's what I got: 
First was "stay for T2" and after:

https://puu.sh/F5kTB/2f673c286a.png 

Then P22 Auto optics, which seems to be fine. Next, I suppose it must be the CSI pad here, but it didn't show up:

https://puu.sh/F5kU1/c26cf4d167.png 

After that, the only thing i get from increase the state (4: Inc State, as you told me to do) is this:

https://puu.sh/F5kUD/729a6d1d95.png 
https://puu.sh/F5kVb/798607ee95.png 
https://puu.sh/F5kVs/8402f6de33.png

**Comment by indy91** [comment] 2020-01-30 17:27
It has a "thread started" and then a "thread busy" message, and no "Thread Ended". That means it started the calculations for (probably) the Ascent PAD but there is some kind of issue with it and it just never stops iterating. That will also stop further calculations from working.

I guess I'll switch to the exact same version as you are using (revision 1483) and will try it there. As it seems to work for me now it could be some bug that only exists in that version. Surprising to me as I didn't touch anything for the Ascent PAD, but I'll see.

**Comment by RL77** [comment] 2020-01-30 18:35
Ok, Thanks!

**Comment by indy91** [comment] 2020-01-30 18:51
Bad news, I can't even reproduce this issue in revision 1483. So as I can see in your pictures the first Ascent PAD ends up with all zeros for the TIG and I guess the CSI PAD calculation then fails completely and never shows up as it needs good numbers from the ascent calculation (mainly the liftoff time). Why that happens though, no idea.

**Comment by RL77** [comment] 2020-01-30 19:13
You think i can fix that by instaling  version 1482, and run the file I gave you, right after landing? I think it probably won't ... because you say it doesn't happen in version 1483 when you tested it. It must have been some error that occurred during the mission. I was unlucky.

**Comment by RL77** [comment] 2020-01-30 21:24
Hey guess what happened :D! I did what I said in the previous comment! I installed revision 1482 and it is already good! Don't ask me why, look:

https://puu.sh/F5pbq/3ac3594cde.png

Instaled revision 1482 and loaded the save file I sent you! Started the checklist from there and here is the pad . I made  a save just before the ascent pad  show up! Do you want me to send it to you to analyze? Just say! Going to continue!

**Comment by RL77** [comment] 2020-01-31 01:56
Just to inform you, I made the checklist until I turned off the LM. I'm at GET 105h30mim, first rest period. Everything went normally with the Pads!

**Comment by indy91** [comment] 2020-01-31 11:52
I have the feeling that sometimes builds are just faulty, without any specific bug in the code. Maybe it has to do with the modules being built for Orbiter 2016, while we are developing for the Orbiter Beta. I don't know. There are certain issues I have never had, maybe because, as a developer, I am building the modules myself with Visual Studio. I will feel a lot better when something like Orbiter 2020 will be released and we can develop specifically for that version.

**Comment by Thymo-** [comment] 2020-04-15 13:32
If the issue is not already resolved they will mostly likely be with a new Orbiter release. Closing.

**Closed by Thymo-** 2020-04-15 13:32 UTC

**Comment by Thymo-** [comment] 2020-04-15 13:34
Fixed in Orbiter according to @indy91
